domain: home
uid: gw-modbus0
mqtt:
  brokerUrl: mqtt://127.0.0.1
  topicFormat: fancy
modbus:
  main: 
    connectionString: serial:/dev/ttyS4
    baudRate: 9600
heartbeat:
  interval: 2000
devices:
  kitchen-light1: # Světlo v kuchyni
    alias: light
    checkInterval: 1000
    meta:
      type: device/light, light
      name: Světlo
      description: Hlavní světlo kuchyně
      room: kitchen
      product: Modbus relay
      vendor: CallMeFoxie
    registers:
      switch: # Vypínač
        access: RW
        pool: kitchen-sw
        field: 1
      current: # Měřič proudu světla
        access: R
        pool: kitchen-sw
        field: 0
      #brightness: # Jas
      #  access: RW
      #  slave: 2
      #  address: 1
      #color_temp: # Teplota
      #  access: RW
      #  slave: 2
      #  address: 2
  bathroom-light1: # Světlo v koupelně
    bus: main
    alias: light
    checkInterval: 1000
    meta:
      room: bathroom
    registers:
      switch: # Vypínač
        access: RW
        pool: bathroom-sw
        address: 1
      switch1: # Vypínač
        access: RW
        pool: bathroom-sw
        address: 1
      switch2: # Vypínač
        access: RW
        pool: bathroom-sw
        address: 1
      switch3: # Vypínač
        access: RW
        pool: bathroom-sw
        address: 1
  #    current: # Měřič proudu světla
  #      access: R
  #      slave: 3
  #      address: 0
  #    brightness: # Jas
  #      access: RW
  #      slave: 4
  #      address: 1
  #    color_temp: # Teplota
  #      access: RW
  #      slave: 4
  #      address: 2
pools:
  - name: kitchen-sw
    bus: main
    unit: 255
    length: 3
  - name: bathroom-sw
    bus: main
    unit: 254
    length: 3
