domain: home/modbus0
uid: GW-modbus-gw0
mqtt:
  brokerUrl: mqtt://127.0.0.1
modbus:
  main: 
    type: serial
    connectionString: /dev/ttyS4
    baudRate: 9600
devices:
  lgt-kitchen-light0: # Světlo v kuchyni
    bus: main
    checkInterval: 1000
    meta:
      type: device/light, light
      name: Kuchyně - Světlo
      product: Modbus relay
      vendor: CallMeFoxie
      location: kitchen
    registers:
      switch: # Vypínač
        access: RW
        slave: 255
        address: 1
      current: # Měřič proudu světla
        access: R
        slave: 255
        address: 0
      #brightness: # Jas
      #  access: RW
      #  slave: 2
      #  address: 1
      #color_temp: # Teplota
      #  access: RW
      #  slave: 2
      #  address: 2
  bathroomlight0: # Světlo v koupelně
    bus: main
    checkInterval: 1000
    registers:
      switch: # Vypínač
        access: RW
        slave: 255
        address: 1
      switch1: # Vypínač
        access: RW
        slave: 255
        address: 1
      switch2: # Vypínač
        access: RW
        slave: 255
        address: 1
      switch3: # Vypínač
        access: RW
        slave: 255
        address: 1
  #    current: # Měřič proudu světla
  #      access: R
  #      slave: 3
  #      address: 0
  #    brightness: # Jas
  #      access: RW
  #      slave: 4
  #      address: 1
  #    color_temp: # Teplota
  #      access: RW
  #      slave: 4
  #      address: 2
